// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: basaltpb/blob.proto

package basaltpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Blob_Create_FullMethodName = "/basaltpb.Blob/Create"
	Blob_Seal_FullMethodName   = "/basaltpb.Blob/Seal"
	Blob_Delete_FullMethodName = "/basaltpb.Blob/Delete"
	Blob_Stat_FullMethodName   = "/basaltpb.Blob/Stat"
)

// BlobClient is the client API for Blob service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Blob handles control operations on a single blob server.
// Each blob server stores object replicas on local disks.
//
// Data operations (Append, Read) use a separate custom TCP protocol
// for lower overhead - see internal/blob/protocol.go for details.
type BlobClient interface {
	// Create initializes a new object on this blob server.
	Create(ctx context.Context, in *BlobCreateRequest, opts ...grpc.CallOption) (*BlobCreateResponse, error)
	// Seal marks an object as immutable on this replica.
	Seal(ctx context.Context, in *BlobSealRequest, opts ...grpc.CallOption) (*BlobSealResponse, error)
	// Delete removes an object from this blob server.
	Delete(ctx context.Context, in *BlobDeleteRequest, opts ...grpc.CallOption) (*BlobDeleteResponse, error)
	// Stat returns metadata about an object.
	Stat(ctx context.Context, in *BlobStatRequest, opts ...grpc.CallOption) (*BlobStatResponse, error)
}

type blobClient struct {
	cc grpc.ClientConnInterface
}

func NewBlobClient(cc grpc.ClientConnInterface) BlobClient {
	return &blobClient{cc}
}

func (c *blobClient) Create(ctx context.Context, in *BlobCreateRequest, opts ...grpc.CallOption) (*BlobCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlobCreateResponse)
	err := c.cc.Invoke(ctx, Blob_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobClient) Seal(ctx context.Context, in *BlobSealRequest, opts ...grpc.CallOption) (*BlobSealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlobSealResponse)
	err := c.cc.Invoke(ctx, Blob_Seal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobClient) Delete(ctx context.Context, in *BlobDeleteRequest, opts ...grpc.CallOption) (*BlobDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlobDeleteResponse)
	err := c.cc.Invoke(ctx, Blob_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobClient) Stat(ctx context.Context, in *BlobStatRequest, opts ...grpc.CallOption) (*BlobStatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlobStatResponse)
	err := c.cc.Invoke(ctx, Blob_Stat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlobServer is the server API for Blob service.
// All implementations must embed UnimplementedBlobServer
// for forward compatibility.
//
// Blob handles control operations on a single blob server.
// Each blob server stores object replicas on local disks.
//
// Data operations (Append, Read) use a separate custom TCP protocol
// for lower overhead - see internal/blob/protocol.go for details.
type BlobServer interface {
	// Create initializes a new object on this blob server.
	Create(context.Context, *BlobCreateRequest) (*BlobCreateResponse, error)
	// Seal marks an object as immutable on this replica.
	Seal(context.Context, *BlobSealRequest) (*BlobSealResponse, error)
	// Delete removes an object from this blob server.
	Delete(context.Context, *BlobDeleteRequest) (*BlobDeleteResponse, error)
	// Stat returns metadata about an object.
	Stat(context.Context, *BlobStatRequest) (*BlobStatResponse, error)
	mustEmbedUnimplementedBlobServer()
}

// UnimplementedBlobServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlobServer struct{}

func (UnimplementedBlobServer) Create(context.Context, *BlobCreateRequest) (*BlobCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedBlobServer) Seal(context.Context, *BlobSealRequest) (*BlobSealResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Seal not implemented")
}
func (UnimplementedBlobServer) Delete(context.Context, *BlobDeleteRequest) (*BlobDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedBlobServer) Stat(context.Context, *BlobStatRequest) (*BlobStatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedBlobServer) mustEmbedUnimplementedBlobServer() {}
func (UnimplementedBlobServer) testEmbeddedByValue()              {}

// UnsafeBlobServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlobServer will
// result in compilation errors.
type UnsafeBlobServer interface {
	mustEmbedUnimplementedBlobServer()
}

func RegisterBlobServer(s grpc.ServiceRegistrar, srv BlobServer) {
	// If the following call panics, it indicates UnimplementedBlobServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Blob_ServiceDesc, srv)
}

func _Blob_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlobCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blob_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobServer).Create(ctx, req.(*BlobCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blob_Seal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlobSealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobServer).Seal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blob_Seal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobServer).Seal(ctx, req.(*BlobSealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blob_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlobDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blob_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobServer).Delete(ctx, req.(*BlobDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blob_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlobStatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Blob_Stat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobServer).Stat(ctx, req.(*BlobStatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Blob_ServiceDesc is the grpc.ServiceDesc for Blob service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Blob_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "basaltpb.Blob",
	HandlerType: (*BlobServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Blob_Create_Handler,
		},
		{
			MethodName: "Seal",
			Handler:    _Blob_Seal_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Blob_Delete_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _Blob_Stat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "basaltpb/blob.proto",
}
