// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: basaltpb/compactor.proto

package basaltpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlushRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	MountId *MountID               `protobuf:"bytes,1,opt,name=mount_id,json=mountId,proto3" json:"mount_id,omitempty"`
	// Objects containing the memtable data to flush.
	MemtableObjects []*ObjectID `protobuf:"bytes,2,rep,name=memtable_objects,json=memtableObjects,proto3" json:"memtable_objects,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FlushRequest) Reset() {
	*x = FlushRequest{}
	mi := &file_basaltpb_compactor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushRequest) ProtoMessage() {}

func (x *FlushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basaltpb_compactor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushRequest.ProtoReflect.Descriptor instead.
func (*FlushRequest) Descriptor() ([]byte, []int) {
	return file_basaltpb_compactor_proto_rawDescGZIP(), []int{0}
}

func (x *FlushRequest) GetMountId() *MountID {
	if x != nil {
		return x.MountId
	}
	return nil
}

func (x *FlushRequest) GetMemtableObjects() []*ObjectID {
	if x != nil {
		return x.MemtableObjects
	}
	return nil
}

type FlushResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New SSTable objects created by the flush.
	OutputTables  []*ObjectMeta `protobuf:"bytes,1,rep,name=output_tables,json=outputTables,proto3" json:"output_tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushResponse) Reset() {
	*x = FlushResponse{}
	mi := &file_basaltpb_compactor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushResponse) ProtoMessage() {}

func (x *FlushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basaltpb_compactor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushResponse.ProtoReflect.Descriptor instead.
func (*FlushResponse) Descriptor() ([]byte, []int) {
	return file_basaltpb_compactor_proto_rawDescGZIP(), []int{1}
}

func (x *FlushResponse) GetOutputTables() []*ObjectMeta {
	if x != nil {
		return x.OutputTables
	}
	return nil
}

type CompactRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	MountId *MountID               `protobuf:"bytes,1,opt,name=mount_id,json=mountId,proto3" json:"mount_id,omitempty"`
	// Input SSTable objects to compact.
	InputTables []*ObjectID `protobuf:"bytes,2,rep,name=input_tables,json=inputTables,proto3" json:"input_tables,omitempty"`
	// Target level for the compaction output.
	OutputLevel   int32 `protobuf:"varint,3,opt,name=output_level,json=outputLevel,proto3" json:"output_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactRequest) Reset() {
	*x = CompactRequest{}
	mi := &file_basaltpb_compactor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactRequest) ProtoMessage() {}

func (x *CompactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basaltpb_compactor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactRequest.ProtoReflect.Descriptor instead.
func (*CompactRequest) Descriptor() ([]byte, []int) {
	return file_basaltpb_compactor_proto_rawDescGZIP(), []int{2}
}

func (x *CompactRequest) GetMountId() *MountID {
	if x != nil {
		return x.MountId
	}
	return nil
}

func (x *CompactRequest) GetInputTables() []*ObjectID {
	if x != nil {
		return x.InputTables
	}
	return nil
}

func (x *CompactRequest) GetOutputLevel() int32 {
	if x != nil {
		return x.OutputLevel
	}
	return 0
}

type CompactResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New SSTable objects created by the compaction.
	OutputTables  []*ObjectMeta `protobuf:"bytes,1,rep,name=output_tables,json=outputTables,proto3" json:"output_tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactResponse) Reset() {
	*x = CompactResponse{}
	mi := &file_basaltpb_compactor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactResponse) ProtoMessage() {}

func (x *CompactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basaltpb_compactor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactResponse.ProtoReflect.Descriptor instead.
func (*CompactResponse) Descriptor() ([]byte, []int) {
	return file_basaltpb_compactor_proto_rawDescGZIP(), []int{3}
}

func (x *CompactResponse) GetOutputTables() []*ObjectMeta {
	if x != nil {
		return x.OutputTables
	}
	return nil
}

var File_basaltpb_compactor_proto protoreflect.FileDescriptor

const file_basaltpb_compactor_proto_rawDesc = "" +
	"\n" +
	"\x18basaltpb/compactor.proto\x12\bbasaltpb\x1a\x15basaltpb/common.proto\"{\n" +
	"\fFlushRequest\x12,\n" +
	"\bmount_id\x18\x01 \x01(\v2\x11.basaltpb.MountIDR\amountId\x12=\n" +
	"\x10memtable_objects\x18\x02 \x03(\v2\x12.basaltpb.ObjectIDR\x0fmemtableObjects\"J\n" +
	"\rFlushResponse\x129\n" +
	"\routput_tables\x18\x01 \x03(\v2\x14.basaltpb.ObjectMetaR\foutputTables\"\x98\x01\n" +
	"\x0eCompactRequest\x12,\n" +
	"\bmount_id\x18\x01 \x01(\v2\x11.basaltpb.MountIDR\amountId\x125\n" +
	"\finput_tables\x18\x02 \x03(\v2\x12.basaltpb.ObjectIDR\vinputTables\x12!\n" +
	"\foutput_level\x18\x03 \x01(\x05R\voutputLevel\"L\n" +
	"\x0fCompactResponse\x129\n" +
	"\routput_tables\x18\x01 \x03(\v2\x14.basaltpb.ObjectMetaR\foutputTables2\x85\x01\n" +
	"\tCompactor\x128\n" +
	"\x05Flush\x12\x16.basaltpb.FlushRequest\x1a\x17.basaltpb.FlushResponse\x12>\n" +
	"\aCompact\x12\x18.basaltpb.CompactRequest\x1a\x19.basaltpb.CompactResponseB.Z,github.com/cockroachdb/basaltclient/basaltpbb\x06proto3"

var (
	file_basaltpb_compactor_proto_rawDescOnce sync.Once
	file_basaltpb_compactor_proto_rawDescData []byte
)

func file_basaltpb_compactor_proto_rawDescGZIP() []byte {
	file_basaltpb_compactor_proto_rawDescOnce.Do(func() {
		file_basaltpb_compactor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_basaltpb_compactor_proto_rawDesc), len(file_basaltpb_compactor_proto_rawDesc)))
	})
	return file_basaltpb_compactor_proto_rawDescData
}

var file_basaltpb_compactor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_basaltpb_compactor_proto_goTypes = []any{
	(*FlushRequest)(nil),    // 0: basaltpb.FlushRequest
	(*FlushResponse)(nil),   // 1: basaltpb.FlushResponse
	(*CompactRequest)(nil),  // 2: basaltpb.CompactRequest
	(*CompactResponse)(nil), // 3: basaltpb.CompactResponse
	(*MountID)(nil),         // 4: basaltpb.MountID
	(*ObjectID)(nil),        // 5: basaltpb.ObjectID
	(*ObjectMeta)(nil),      // 6: basaltpb.ObjectMeta
}
var file_basaltpb_compactor_proto_depIdxs = []int32{
	4, // 0: basaltpb.FlushRequest.mount_id:type_name -> basaltpb.MountID
	5, // 1: basaltpb.FlushRequest.memtable_objects:type_name -> basaltpb.ObjectID
	6, // 2: basaltpb.FlushResponse.output_tables:type_name -> basaltpb.ObjectMeta
	4, // 3: basaltpb.CompactRequest.mount_id:type_name -> basaltpb.MountID
	5, // 4: basaltpb.CompactRequest.input_tables:type_name -> basaltpb.ObjectID
	6, // 5: basaltpb.CompactResponse.output_tables:type_name -> basaltpb.ObjectMeta
	0, // 6: basaltpb.Compactor.Flush:input_type -> basaltpb.FlushRequest
	2, // 7: basaltpb.Compactor.Compact:input_type -> basaltpb.CompactRequest
	1, // 8: basaltpb.Compactor.Flush:output_type -> basaltpb.FlushResponse
	3, // 9: basaltpb.Compactor.Compact:output_type -> basaltpb.CompactResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_basaltpb_compactor_proto_init() }
func file_basaltpb_compactor_proto_init() {
	if File_basaltpb_compactor_proto != nil {
		return
	}
	file_basaltpb_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_basaltpb_compactor_proto_rawDesc), len(file_basaltpb_compactor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_basaltpb_compactor_proto_goTypes,
		DependencyIndexes: file_basaltpb_compactor_proto_depIdxs,
		MessageInfos:      file_basaltpb_compactor_proto_msgTypes,
	}.Build()
	File_basaltpb_compactor_proto = out.File
	file_basaltpb_compactor_proto_goTypes = nil
	file_basaltpb_compactor_proto_depIdxs = nil
}
