// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: basaltpb/compactor.proto

package basaltpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Compactor_Flush_FullMethodName   = "/basaltpb.Compactor/Flush"
	Compactor_Compact_FullMethodName = "/basaltpb.Compactor/Compact"
)

// CompactorClient is the client API for Compactor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Compactor is the gRPC service for remote flush and compaction operations.
type CompactorClient interface {
	// Flush replays WAL objects and creates L0 SSTables.
	Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error)
	// Compact merges input SSTables and creates output SSTables.
	Compact(ctx context.Context, in *CompactRequest, opts ...grpc.CallOption) (*CompactResponse, error)
}

type compactorClient struct {
	cc grpc.ClientConnInterface
}

func NewCompactorClient(cc grpc.ClientConnInterface) CompactorClient {
	return &compactorClient{cc}
}

func (c *compactorClient) Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushResponse)
	err := c.cc.Invoke(ctx, Compactor_Flush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compactorClient) Compact(ctx context.Context, in *CompactRequest, opts ...grpc.CallOption) (*CompactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompactResponse)
	err := c.cc.Invoke(ctx, Compactor_Compact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompactorServer is the server API for Compactor service.
// All implementations must embed UnimplementedCompactorServer
// for forward compatibility.
//
// Compactor is the gRPC service for remote flush and compaction operations.
type CompactorServer interface {
	// Flush replays WAL objects and creates L0 SSTables.
	Flush(context.Context, *FlushRequest) (*FlushResponse, error)
	// Compact merges input SSTables and creates output SSTables.
	Compact(context.Context, *CompactRequest) (*CompactResponse, error)
	mustEmbedUnimplementedCompactorServer()
}

// UnimplementedCompactorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCompactorServer struct{}

func (UnimplementedCompactorServer) Flush(context.Context, *FlushRequest) (*FlushResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Flush not implemented")
}
func (UnimplementedCompactorServer) Compact(context.Context, *CompactRequest) (*CompactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Compact not implemented")
}
func (UnimplementedCompactorServer) mustEmbedUnimplementedCompactorServer() {}
func (UnimplementedCompactorServer) testEmbeddedByValue()                   {}

// UnsafeCompactorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompactorServer will
// result in compilation errors.
type UnsafeCompactorServer interface {
	mustEmbedUnimplementedCompactorServer()
}

func RegisterCompactorServer(s grpc.ServiceRegistrar, srv CompactorServer) {
	// If the following call panics, it indicates UnimplementedCompactorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Compactor_ServiceDesc, srv)
}

func _Compactor_Flush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompactorServer).Flush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Compactor_Flush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompactorServer).Flush(ctx, req.(*FlushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Compactor_Compact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompactorServer).Compact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Compactor_Compact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompactorServer).Compact(ctx, req.(*CompactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Compactor_ServiceDesc is the grpc.ServiceDesc for Compactor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Compactor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "basaltpb.Compactor",
	HandlerType: (*CompactorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Flush",
			Handler:    _Compactor_Flush_Handler,
		},
		{
			MethodName: "Compact",
			Handler:    _Compactor_Compact_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "basaltpb/compactor.proto",
}
