// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: basaltpb/controller.proto

package basaltpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier for this Pebble instance (e.g., node ID + store ID).
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// Availability zone of the mounting node.
	Az            string `protobuf:"bytes,2,opt,name=az,proto3" json:"az,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountRequest) Reset() {
	*x = MountRequest{}
	mi := &file_basaltpb_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountRequest) ProtoMessage() {}

func (x *MountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basaltpb_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountRequest.ProtoReflect.Descriptor instead.
func (*MountRequest) Descriptor() ([]byte, []int) {
	return file_basaltpb_controller_proto_rawDescGZIP(), []int{0}
}

func (x *MountRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *MountRequest) GetAz() string {
	if x != nil {
		return x.Az
	}
	return ""
}

type MountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique mount ID for this session.
	MountId       *MountID `protobuf:"bytes,1,opt,name=mount_id,json=mountId,proto3" json:"mount_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountResponse) Reset() {
	*x = MountResponse{}
	mi := &file_basaltpb_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountResponse) ProtoMessage() {}

func (x *MountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basaltpb_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountResponse.ProtoReflect.Descriptor instead.
func (*MountResponse) Descriptor() ([]byte, []int) {
	return file_basaltpb_controller_proto_rawDescGZIP(), []int{1}
}

func (x *MountResponse) GetMountId() *MountID {
	if x != nil {
		return x.MountId
	}
	return nil
}

type UnmountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountId       *MountID               `protobuf:"bytes,1,opt,name=mount_id,json=mountId,proto3" json:"mount_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmountRequest) Reset() {
	*x = UnmountRequest{}
	mi := &file_basaltpb_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountRequest) ProtoMessage() {}

func (x *UnmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basaltpb_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountRequest.ProtoReflect.Descriptor instead.
func (*UnmountRequest) Descriptor() ([]byte, []int) {
	return file_basaltpb_controller_proto_rawDescGZIP(), []int{2}
}

func (x *UnmountRequest) GetMountId() *MountID {
	if x != nil {
		return x.MountId
	}
	return nil
}

type UnmountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmountResponse) Reset() {
	*x = UnmountResponse{}
	mi := &file_basaltpb_controller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountResponse) ProtoMessage() {}

func (x *UnmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basaltpb_controller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountResponse.ProtoReflect.Descriptor instead.
func (*UnmountResponse) Descriptor() ([]byte, []int) {
	return file_basaltpb_controller_proto_rawDescGZIP(), []int{3}
}

type CreateRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	MountId *MountID               `protobuf:"bytes,1,opt,name=mount_id,json=mountId,proto3" json:"mount_id,omitempty"`
	// Logical path/name for the object (e.g., "000001.sst").
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Desired replication factor.
	Replication   int32 `protobuf:"varint,3,opt,name=replication,proto3" json:"replication,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_basaltpb_controller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basaltpb_controller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_basaltpb_controller_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRequest) GetMountId() *MountID {
	if x != nil {
		return x.MountId
	}
	return nil
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRequest) GetReplication() int32 {
	if x != nil {
		return x.Replication
	}
	return 0
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ObjectMeta            `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_basaltpb_controller_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basaltpb_controller_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_basaltpb_controller_proto_rawDescGZIP(), []int{5}
}

func (x *CreateResponse) GetMeta() *ObjectMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type LookupRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	MountId *MountID               `protobuf:"bytes,1,opt,name=mount_id,json=mountId,proto3" json:"mount_id,omitempty"`
	// Object to look up by ID or name.
	//
	// Types that are valid to be assigned to Key:
	//
	//	*LookupRequest_Id
	//	*LookupRequest_Name
	Key           isLookupRequest_Key `protobuf_oneof:"key"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_basaltpb_controller_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basaltpb_controller_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_basaltpb_controller_proto_rawDescGZIP(), []int{6}
}

func (x *LookupRequest) GetMountId() *MountID {
	if x != nil {
		return x.MountId
	}
	return nil
}

func (x *LookupRequest) GetKey() isLookupRequest_Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LookupRequest) GetId() *ObjectID {
	if x != nil {
		if x, ok := x.Key.(*LookupRequest_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *LookupRequest) GetName() string {
	if x != nil {
		if x, ok := x.Key.(*LookupRequest_Name); ok {
			return x.Name
		}
	}
	return ""
}

type isLookupRequest_Key interface {
	isLookupRequest_Key()
}

type LookupRequest_Id struct {
	Id *ObjectID `protobuf:"bytes,2,opt,name=id,proto3,oneof"`
}

type LookupRequest_Name struct {
	Name string `protobuf:"bytes,3,opt,name=name,proto3,oneof"`
}

func (*LookupRequest_Id) isLookupRequest_Key() {}

func (*LookupRequest_Name) isLookupRequest_Key() {}

type LookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ObjectMeta            `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	mi := &file_basaltpb_controller_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basaltpb_controller_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_basaltpb_controller_proto_rawDescGZIP(), []int{7}
}

func (x *LookupResponse) GetMeta() *ObjectMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountId       *MountID               `protobuf:"bytes,1,opt,name=mount_id,json=mountId,proto3" json:"mount_id,omitempty"`
	Id            *ObjectID              `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_basaltpb_controller_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basaltpb_controller_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_basaltpb_controller_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRequest) GetMountId() *MountID {
	if x != nil {
		return x.MountId
	}
	return nil
}

func (x *DeleteRequest) GetId() *ObjectID {
	if x != nil {
		return x.Id
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_basaltpb_controller_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basaltpb_controller_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_basaltpb_controller_proto_rawDescGZIP(), []int{9}
}

type SealRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	MountId *MountID               `protobuf:"bytes,1,opt,name=mount_id,json=mountId,proto3" json:"mount_id,omitempty"`
	Id      *ObjectID              `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Final size of the object.
	Size          int64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SealRequest) Reset() {
	*x = SealRequest{}
	mi := &file_basaltpb_controller_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealRequest) ProtoMessage() {}

func (x *SealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basaltpb_controller_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealRequest.ProtoReflect.Descriptor instead.
func (*SealRequest) Descriptor() ([]byte, []int) {
	return file_basaltpb_controller_proto_rawDescGZIP(), []int{10}
}

func (x *SealRequest) GetMountId() *MountID {
	if x != nil {
		return x.MountId
	}
	return nil
}

func (x *SealRequest) GetId() *ObjectID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SealRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SealResponse) Reset() {
	*x = SealResponse{}
	mi := &file_basaltpb_controller_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealResponse) ProtoMessage() {}

func (x *SealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basaltpb_controller_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealResponse.ProtoReflect.Descriptor instead.
func (*SealResponse) Descriptor() ([]byte, []int) {
	return file_basaltpb_controller_proto_rawDescGZIP(), []int{11}
}

var File_basaltpb_controller_proto protoreflect.FileDescriptor

const file_basaltpb_controller_proto_rawDesc = "" +
	"\n" +
	"\x19basaltpb/controller.proto\x12\bbasaltpb\x1a\x15basaltpb/common.proto\"?\n" +
	"\fMountRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x0e\n" +
	"\x02az\x18\x02 \x01(\tR\x02az\"=\n" +
	"\rMountResponse\x12,\n" +
	"\bmount_id\x18\x01 \x01(\v2\x11.basaltpb.MountIDR\amountId\">\n" +
	"\x0eUnmountRequest\x12,\n" +
	"\bmount_id\x18\x01 \x01(\v2\x11.basaltpb.MountIDR\amountId\"\x11\n" +
	"\x0fUnmountResponse\"s\n" +
	"\rCreateRequest\x12,\n" +
	"\bmount_id\x18\x01 \x01(\v2\x11.basaltpb.MountIDR\amountId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vreplication\x18\x03 \x01(\x05R\vreplication\":\n" +
	"\x0eCreateResponse\x12(\n" +
	"\x04meta\x18\x01 \x01(\v2\x14.basaltpb.ObjectMetaR\x04meta\"\x80\x01\n" +
	"\rLookupRequest\x12,\n" +
	"\bmount_id\x18\x01 \x01(\v2\x11.basaltpb.MountIDR\amountId\x12$\n" +
	"\x02id\x18\x02 \x01(\v2\x12.basaltpb.ObjectIDH\x00R\x02id\x12\x14\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04nameB\x05\n" +
	"\x03key\":\n" +
	"\x0eLookupResponse\x12(\n" +
	"\x04meta\x18\x01 \x01(\v2\x14.basaltpb.ObjectMetaR\x04meta\"a\n" +
	"\rDeleteRequest\x12,\n" +
	"\bmount_id\x18\x01 \x01(\v2\x11.basaltpb.MountIDR\amountId\x12\"\n" +
	"\x02id\x18\x02 \x01(\v2\x12.basaltpb.ObjectIDR\x02id\"\x10\n" +
	"\x0eDeleteResponse\"s\n" +
	"\vSealRequest\x12,\n" +
	"\bmount_id\x18\x01 \x01(\v2\x11.basaltpb.MountIDR\amountId\x12\"\n" +
	"\x02id\x18\x02 \x01(\v2\x12.basaltpb.ObjectIDR\x02id\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"\x0e\n" +
	"\fSealResponse2\xf4\x02\n" +
	"\n" +
	"Controller\x128\n" +
	"\x05Mount\x12\x16.basaltpb.MountRequest\x1a\x17.basaltpb.MountResponse\x12>\n" +
	"\aUnmount\x12\x18.basaltpb.UnmountRequest\x1a\x19.basaltpb.UnmountResponse\x12;\n" +
	"\x06Create\x12\x17.basaltpb.CreateRequest\x1a\x18.basaltpb.CreateResponse\x12;\n" +
	"\x06Lookup\x12\x17.basaltpb.LookupRequest\x1a\x18.basaltpb.LookupResponse\x12;\n" +
	"\x06Delete\x12\x17.basaltpb.DeleteRequest\x1a\x18.basaltpb.DeleteResponse\x125\n" +
	"\x04Seal\x12\x15.basaltpb.SealRequest\x1a\x16.basaltpb.SealResponseB.Z,github.com/cockroachdb/basaltclient/basaltpbb\x06proto3"

var (
	file_basaltpb_controller_proto_rawDescOnce sync.Once
	file_basaltpb_controller_proto_rawDescData []byte
)

func file_basaltpb_controller_proto_rawDescGZIP() []byte {
	file_basaltpb_controller_proto_rawDescOnce.Do(func() {
		file_basaltpb_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_basaltpb_controller_proto_rawDesc), len(file_basaltpb_controller_proto_rawDesc)))
	})
	return file_basaltpb_controller_proto_rawDescData
}

var file_basaltpb_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_basaltpb_controller_proto_goTypes = []any{
	(*MountRequest)(nil),    // 0: basaltpb.MountRequest
	(*MountResponse)(nil),   // 1: basaltpb.MountResponse
	(*UnmountRequest)(nil),  // 2: basaltpb.UnmountRequest
	(*UnmountResponse)(nil), // 3: basaltpb.UnmountResponse
	(*CreateRequest)(nil),   // 4: basaltpb.CreateRequest
	(*CreateResponse)(nil),  // 5: basaltpb.CreateResponse
	(*LookupRequest)(nil),   // 6: basaltpb.LookupRequest
	(*LookupResponse)(nil),  // 7: basaltpb.LookupResponse
	(*DeleteRequest)(nil),   // 8: basaltpb.DeleteRequest
	(*DeleteResponse)(nil),  // 9: basaltpb.DeleteResponse
	(*SealRequest)(nil),     // 10: basaltpb.SealRequest
	(*SealResponse)(nil),    // 11: basaltpb.SealResponse
	(*MountID)(nil),         // 12: basaltpb.MountID
	(*ObjectMeta)(nil),      // 13: basaltpb.ObjectMeta
	(*ObjectID)(nil),        // 14: basaltpb.ObjectID
}
var file_basaltpb_controller_proto_depIdxs = []int32{
	12, // 0: basaltpb.MountResponse.mount_id:type_name -> basaltpb.MountID
	12, // 1: basaltpb.UnmountRequest.mount_id:type_name -> basaltpb.MountID
	12, // 2: basaltpb.CreateRequest.mount_id:type_name -> basaltpb.MountID
	13, // 3: basaltpb.CreateResponse.meta:type_name -> basaltpb.ObjectMeta
	12, // 4: basaltpb.LookupRequest.mount_id:type_name -> basaltpb.MountID
	14, // 5: basaltpb.LookupRequest.id:type_name -> basaltpb.ObjectID
	13, // 6: basaltpb.LookupResponse.meta:type_name -> basaltpb.ObjectMeta
	12, // 7: basaltpb.DeleteRequest.mount_id:type_name -> basaltpb.MountID
	14, // 8: basaltpb.DeleteRequest.id:type_name -> basaltpb.ObjectID
	12, // 9: basaltpb.SealRequest.mount_id:type_name -> basaltpb.MountID
	14, // 10: basaltpb.SealRequest.id:type_name -> basaltpb.ObjectID
	0,  // 11: basaltpb.Controller.Mount:input_type -> basaltpb.MountRequest
	2,  // 12: basaltpb.Controller.Unmount:input_type -> basaltpb.UnmountRequest
	4,  // 13: basaltpb.Controller.Create:input_type -> basaltpb.CreateRequest
	6,  // 14: basaltpb.Controller.Lookup:input_type -> basaltpb.LookupRequest
	8,  // 15: basaltpb.Controller.Delete:input_type -> basaltpb.DeleteRequest
	10, // 16: basaltpb.Controller.Seal:input_type -> basaltpb.SealRequest
	1,  // 17: basaltpb.Controller.Mount:output_type -> basaltpb.MountResponse
	3,  // 18: basaltpb.Controller.Unmount:output_type -> basaltpb.UnmountResponse
	5,  // 19: basaltpb.Controller.Create:output_type -> basaltpb.CreateResponse
	7,  // 20: basaltpb.Controller.Lookup:output_type -> basaltpb.LookupResponse
	9,  // 21: basaltpb.Controller.Delete:output_type -> basaltpb.DeleteResponse
	11, // 22: basaltpb.Controller.Seal:output_type -> basaltpb.SealResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_basaltpb_controller_proto_init() }
func file_basaltpb_controller_proto_init() {
	if File_basaltpb_controller_proto != nil {
		return
	}
	file_basaltpb_common_proto_init()
	file_basaltpb_controller_proto_msgTypes[6].OneofWrappers = []any{
		(*LookupRequest_Id)(nil),
		(*LookupRequest_Name)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_basaltpb_controller_proto_rawDesc), len(file_basaltpb_controller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_basaltpb_controller_proto_goTypes,
		DependencyIndexes: file_basaltpb_controller_proto_depIdxs,
		MessageInfos:      file_basaltpb_controller_proto_msgTypes,
	}.Build()
	File_basaltpb_controller_proto = out.File
	file_basaltpb_controller_proto_goTypes = nil
	file_basaltpb_controller_proto_depIdxs = nil
}
